server:
  port: 8093

spring:
  application:
    name: ms-avaliador-credito
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

mq:
  queues:
    emissao-cartoes: emissao-cartoes
