spring:
  application:
    name: ms-avaliador-credito
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 1
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1

mq:
  queues:
    emissao-cartoes: emissao-cartoes
